#!/usr/bin/lua                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                            
--    put the router in monitor mode    iw phy phy0 interface add mon0 type monitor                                                                                                                                                                         
--    then enable the interface         ifconfig mon0 up                                                                                                                                                                                                    
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                            
function get_packet(line)                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                            
  if not line then                                                                                                                                                                                                                                          
    return nil                                                                                                                                                                                                                                              
  end                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                            
        packet = {}                                                                                                                                                                                                                                         
        packet = string.gsub(line,'['..'>,"'..']','')      -- remove >," from tcpdump results                                                                                                                                                               
                                                                                                                                                                                                                                                            
        words = {}                                                                                                                                                                                                                                          
        for word in packet:gmatch("%S+") do                                                                                                                                                                                                                 
                table.insert(words, word)                                                                                                                                                                                                                   
--              print (words, word)                                                                                                                                                                                                                         
        end                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                            
  return packet, words                                                                                                                                                                                                                                      
end                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                            
function main_loop()                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                            
        local http=require'socket.http'                                                                                                                                                                                                                     
        local packet = {}                                                                                                                                                                                                                                   
        local f                                                                                                                                                                                                                                             
        local last = 0                                                                                                                                                                                                                                      
        local count = 0                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                            
--      lets see what's asking for a connection                                                                                                                                                                                                             
        f = io.popen("tcpdump -en -s 128 -i mon0 type mgt subtype probe-req")                                                                                                                                                                               
                                                                                                                                                                                                                                                            
        DASHmac = 'empty'                                                                                                                                                                                                                                   
        oldmac =  'wack'                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                            
        now = socket.gettime()                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                            
        print ('hello')                                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                            
        while true do                                       -- big loop, waiting for packets                                                                                                                                                                
                                                                                                                                                                                                                                                            
            packet = get_packet(f:read("*l"))           --                                                                                                                                                                                                  
--                      print(packet, '\n')                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                            
--                      for k, v in pairs( words ) do                                                                                                                                                                                                       
--                         print(k, v)                                                                                                                                                                                                                      
--                      end                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                            
                        DASHmac=words[15]                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                            
                        print(count,'   ',now,'  ','        MAC adddress is =  '..DASHmac)                                                                                                                                                                  
                                                                                                                                                                                                                                                            
                        if DASHmac == oldmac then                                                                                                                                                                                                           
                                count = count + 1                                                                                                                                                                                                           
                        else                                                                                                                                                                                                                                
                                print(count,'   ',now, '  ',' repeat MAC adddress is =  '..DASHmac)                                                                                                                                                         
                                count = 0                                                                                                                                                                                                                   
                        end                                                                                                                                                                                                                                                                                                                                                                                                                                                             
                        oldmac = DASHmac                                                                                                                                                                                                            
                                                                                                                                                                                                                                                            
--                      if count > 8 then                                                                                                                                                                                                                   
--                              print('button pushed  '..DASHmac)                                                                                                                                                                                           
--                              body,c,l,h = http.request('http://maker.ifttt.com/trigger/DASHit/with/key/i2dBLihus44EqrVRBLRk3')                                                                                                                           
--                              print(body,c,l,h)                                                                                                                                                                                                           
--                      end                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                            
                        now = socket.gettime()                                                                                                                                                                                                              
                                                                                                                                                                                                                                                            
        end                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                            
        io.close(f)                                                                                                                                                                                                                                         
end                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                            
main_loop()   
